[book]
authors = ["John Doe"]
language = "en"
multilingual = false
src = "src"
title = "My book"

[preprocessor.svgbob]

[preprocessor.graphviz]
command = "mdbook-graphviz"
output-to-file = false

[build]
build-dir = "../htmlbook"                # the directory where the output is placed
create-missing = true             # whether or not to create missing pages
use-default-preprocessors = true
